version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Restore packages
          command:
            dotnet restore
      - run:
          name: Test App
          command:
            dotnet test
      - run:
          name: Build App
          command:
            dotnet build

