version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/runtime:2.2
    steps:
      - checkout
      - run:
          name: Restore packages
          command:
            dotnet restore
      - run:
          name: Test App
          command:
            dotnet test
      - run:
          name: Build App
          command:
            dotnet build

